global_button_border_radius: 
  type: string
  default: 0
  description: 'Example: 10% or 10px'

basic_button_bg:
  default: ''
  description: 'Note: Styling basic buttons will override primary buttons, so you may want to apply primary button styles below as well. Example: #FF0000 or red. '

basic_button_bg_hover:
  default: ''
  description: 'Example: #FF0000 or red'

basic_button_text:
  default: ''
  description: 'Example: #FF0000 or red'

basic_button_text_hover:
  default: ''
  description: 'Example: #FF0000 or red'

primary_button_bg:
  default: ''
  description: 'Note: These are important buttons, like the create topic button in the composer. Example: #FF0000 or red. '

primary_button_bg_hover:
  default: ''
  description: 'Example: #FF0000 or red'

primary_button_text:
  default: ''
  description: 'Example: #FF0000 or red'

primary_button_text_hover:
  default: ''
  description: 'Example: #FF0000 or red'

header_text:
  default: ''
  description: 'Note: These are the primary nav buttons on the top right. Example: #FF0000 or red.'

header_bg:
  default: ''
  description: 'Example: #FF0000 or red'

header_text_hover:
  default: ''
  description: 'Example: #FF0000 or red'

header_bg_hover:
  default: ''
  description: 'Example: #FF0000 or red'

nav_pill_text:
  default: ''
  description: 'Note: Main topic list nav buttons. Example: #FF0000 or red. '

nav_pill_text_hover:
  default: ''
  description: 'Example: #FF0000 or red'

nav_pill_bg_hover:
  default: ''
  description: 'Example: #FF0000 or red'

nav_pill_bg_active:
  default: ''
  description: 'Example: #FF0000 or red'

nav_pill_text_active:
  default: ''
  description: 'Example: #FF0000 or red'

post_controls_bg:
  default: ''
  description: 'Note: Buttons under each post. Example: #FF0000 or red. '

post_controls_bg_hover:
  default: ''
  description: 'Example: #FF0000 or red'

post_controls_text:
  default: ''
  description: 'Example: #FF0000 or red'

post_controls_text_hover:
  default: ''
  description: 'Example: #FF0000 or red'

editor_button_bg: 
  default: ''
  description: 'Note: Buttons in the composer. Example: #FF0000 or red. '

editor_button_bg_hover:
  default: ''
  description: 'Example: #FF0000 or red'

editor_button_text: 
  default: ''
  description: 'Example: #FF0000 or red'

editor_button_text_hover:
  default: ''
  description: 'Example: #FF0000 or red'




